version: '2'
services:
  web:
    command: /bin/sh -c "cd ~/tmp ;npm run dev ;"
    environment:
      - NODE_ENV=development
    build: .
    volumes:
      - ./src:/root/tmp/src
      - ./config:/root/tmp/config
      - ./build:/root/tmp/build
    ports:
      - "8080:8080"
